blogicum/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:pk>/', views.post_detail, name='post_detail'),
    path("category/<slug:category_slug>/", views.category_posts, name='category_posts'),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('pages/', include('pages.urls')),
    # добавляем пустой URL-шаблон для обработки запросов на главную страницу
    path('', include('blog.urls')),
]

blogicum/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about, name='about'),
]

blogicum/blog/models.py
from django.db import models

blogicum/pages/models.py
from django.db import models

# Create your models here.

blogicum/blog/views.py
from django.shortcuts import render

posts = [
    {
        'id': 0,
        'location': 'Остров отчаянья',
        'date': '30 сентября 1659 года',
        'category': 'travel',
        'text': '''Наш корабль, застигнутый в открытом море
                страшным штормом, потерпел крушение.
                Весь экипаж, кроме меня, утонул; я же,
                несчастный Робинзон Крузо, был выброшен
                полумёртвым на берег этого проклятого острова,
                который назвал островом Отчаяния.''',
    },
    {
        'id': 1,
        'location': 'Остров отчаянья',
        'date': '1 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Проснувшись поутру, я увидел, что наш корабль сняло
                с мели приливом и пригнало гораздо ближе к берегу.
                Это подало мне надежду, что, когда ветер стихнет,
                мне удастся добраться до корабля и запастись едой и
                другими необходимыми вещами. Я немного приободрился,
                хотя печаль о погибших товарищах не покидала меня.
                Мне всё думалось, что, останься мы на корабле, мы
                непременно спаслись бы. Теперь из его обломков мы могли бы
                построить баркас, на котором и выбрались бы из этого
                гиблого места.''',
    },
    {
        'id': 2,
        'location': 'Остров отчаянья',
        'date': '25 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Всю ночь и весь день шёл дождь и дул сильный
                порывистый ветер. 25 октября.  Корабль за ночь разбило
                в щепки; на том месте, где он стоял, торчат какие-то
                жалкие обломки,  да и те видны только во время отлива.
                Весь этот день я хлопотал  около вещей: укрывал и
                укутывал их, чтобы не испортились от дождя.''',
    },
]


def index(request):
    templates = 'blog/index.html'
    context = {'posts': posts}
    return render(request, templates, context)


def post_detail(request, pk):
    templates = 'blog/detail.html'
    context = {'post': posts[pk]}
    return render(request, templates, context)


def category_posts(request, category_slug):
    templates = 'blog/category.html'
    context = {'slug': category_slug}
    return render(request, templates, context)

blogicum/pages/views.py
from django.shortcuts import render


def about(request):
    return render(request, 'pages/about.html')


def index(request):
    return render(request, 'pages/index.html')


def contact(request):
    return render(request, 'pages/contact.html')


def rules(request):
    return render(request, 'pages/rules.html')

blogicum/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" 
  content="width=device-width, initial-scale=1">
  <link rel="icon" 
  href="{% static 'img/fav/fav.png' %}" type="image">
  <link rel="apple-touch-icon" sizes="180x180" 
  href="{% static 'img/fav/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" 
  href="{% static 'img/fav/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" 
  href="{% static 'img/fav/favicon-16x16.png' %}">
  <title>{% block title %}О проекте{% endblock %}</title>
</head>
<body>
  <!-- Включение шапки страницы-->
  {% include 'includes/header.html' %}
  <main>
    <!--Основной контент страницы-->
    <div class="container py-5">
      <!-- Включение содержимого конкретной страницы-->
      {% block content %}{% endblock %}
    </div>
  </main>
  <!-- Включение подвала страницы -->
  {% include "includes/footer.html" %}   
</body>
</html>

blogicum/templates/blog/category.html
{% extends 'base.html' %}

{% block title %}Публикации в категории - {{ slug }}{% endblock %}
 
{% block content %}
  <h1>Публикации в категории - {{ slug }}</h1>
{% endblock %}

blogicum/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}{{ post.location }}. {{ post.date }}{% endblock %}

{% block content %}
  <article>
    <ul>
      <li>
        Место: {{ post.location }}
      </li>
      <li>
        Категория: {{ post.date }}
      </li>
      <li>
        Категория: <a href="{{ post.category }}">{{ post.category }}</a>
      </li>
    </ul>
    <p>
      {{ post.text|linebreaksbr }}
    </p>
  </article>
{% endblock %}

blogicum/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}Лента записей{% endblock %}

{% block content %}
  <h1>Лента записей</h1>
  {% for post in posts %}
  <hr>
  <article>
    <ul>
      <li>
        Место: {{ post.location }}
      </li>
      <li>
        Дата: {{ post.date }}
      </li>
      <li>
        Категория: <a href="{{ post.category }}">{{ post.category }}</a>
      </li>
      <!-- Первые 10 слов -->
      <p>
        {{ post.text|truncatewords:10 }}
      </p>
      <a href="{% url 'blog:post_detail' post.id %}">Читать полный текст</a>
    </article>
    {% endfor %}
  {% endlock %}

blogicum/templates/includes/footer.html
<footer>
    <p>Копирайт, год создания</p>
</footer>

blogicum/templates/includes/header.html
{% load static %}
<header>
    <img src="{% static 'img/logo.png' %}" height="50" alt=""> 
  <nav>
    <ul>
      <li>О проекте</li>
    </ul>
  </nav>
</header>

blogicum/templates/pages/about.html
{% extends 'base.html' %}

{% block content %}
  <h1>О проекте</h1>
{% endblock %}